#!/bin/bash
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#helky
helky(){
echo -e $okegreen'[10:10, 7/25/2019] 10 Mey: http://shop-mobi.mygamesonline.org/sky.php
Mau TUTOR INI ?'
echo -e $okegreen'[10:11, 7/25/2019] Helky: Mau sky tapi ini create domain gk?'
echo -e $okegreen'[10:11, 7/25/2019] 10 Mey: Enggak :v'
echo -e $okegreen'[10:11, 7/25/2019] Helky: Bagus kalo engga😍'
echo -e $okegreen'[10:11, 7/25/2019] Helky: Ya udh bahan apa aja yang harus di siapin 🥺'
echo -e $okegreen'[10:12, 7/25/2019] 10 Mey: Ye'
echo -e $okegreen'[10:13, 7/25/2019] 10 Mey: awardspace.com'
echo -e $okegreen'registrasi > masuk ke domain/subdomain > Registrasi subdomainya > Buka File Maneger And Done :v'
echo -e $okegreen'[10:13, 7/25/2019] Helky: Yups🥺'
echo -e $okegreen'[10:13, 7/25/2019] Helky: Njir :v create domain lagi :v'
echo -e $okegreen'[10:13, 7/25/2019] 10 Mey: Ya'
echo -e $okegreen'[10:14, 7/25/2019] 10 Mey: Ywdh gas tuh'
echo -e $okegreen'[10:14, 7/25/2019] Helky: Woke wait :v'
echo -e $okegreen'[10:15, 7/25/2019] Helky: Itu free domain?'
echo -e $okegreen'[10:15, 7/25/2019] Helky: Sampai berapa domain freenya?'
echo -e $okegreen'[10:16, 7/25/2019] 10 Mey: 1'
echo -e $okegreen'[10:16, 7/25/2019] 10 Mey: subdomainya 3'
}
#psct
psct(){
echo -e $okegreen'[09:00, 7/25/2019] 10 Mey: Matery?'
echo -e $okegreen'[09:00, 7/25/2019] 10 Mey: Yang setuju like ;b'
echo -e $okegreen'[09:03, 7/25/2019] +62 812-4906-3162: I like it🤤'
echo -e $okegreen'[09:03, 7/25/2019] +62 812-4906-3162: Gassssddd'
echo -e $okegreen'[09:03, 7/25/2019] +62 812-4906-3162: Materi apa nih?'
echo -e $okegreen'[09:03, 7/25/2019] 10 Mey: Matery apa ?'
echo -e $okegreen'[09:04, 7/25/2019] +62 812-4906-3162: How to make trojan virus with android notepad :v'
echo -e $okegreen'[09:05, 7/25/2019] +62 812-4906-3162: And how to make payload without metasploit :V'
echo -e $okegreen'[09:07, 7/25/2019] +62 852-3637-7016: How to make a jembud lurus :v'
echo -e $okegreen'[09:07, 7/25/2019] +62 812-4906-3162: Use makarizo dude :V'
echo -e $okegreen'[09:07, 7/25/2019] +62 852-3637-7016: And how to make a jembud Panjank'
echo -e $okegreen'[09:07, 7/25/2019] +62 812-4906-3162: Use shampoo metal:V'
echo -e $okegreen'[09:07, 7/25/2019] +62 852-3637-7016: >:V S3 PERTOKOAN'
echo -e $okegreen'[09:08, 7/25/2019] +62 812-4906-3162: MANTAP ANJINK >:V'
echo -e $okegreen'[09:08, 7/25/2019] +62 852-3637-7016: >:V ANJENK'
echo -e $okegreen'[09:08, 7/25/2019] +62 812-4906-3162: Woakaoakaoakaok >:V'
echo -e $okegreen'[09:13, 7/25/2019] 10 Mey: How to create people ?'
echo -e $okegreen'[09:13, 7/25/2019] 10 Mey: Awoakwoakwok'
echo -e $okegreen'[09:15, 7/25/2019] +62 852-3637-7016: :v Akwkaiwkw'
echo -e $okegreen'[09:16, 7/25/2019] 10 Mey: Awoakeosk'
echo -e $okegreen'[09:16, 7/25/2019] +62 812-4906-3162: Zter :v'
echo -e $okegreen'[09:17, 7/25/2019] 10 Mey: @+62 852-3637-7016 ini pro nih'
echo -e $okegreen'[09:18, 7/25/2019] +62 852-3637-7016: W ga tau apa apa :v'
echo -e $okegreen'[09:19, 7/25/2019] 10 Mey: Si clod ? Jadi gamers'
}
#sis
sis(){
    echo -e $okegreen"[09:50, 7/25/2019] 10 Mey: inurl:/kontributor site:"
    echo -e $okegreen"[09:50, 7/25/2019] 10 Mey: Tuh dork kntl"
    echo -e $okegreen"[10:03, 7/25/2019] S1XT33N: Okeh tol"
   echo -e $okegreen"[10:04, 7/25/2019] 10 Mey: ye su"
   echo -e $okegreen"[10:04, 7/25/2019] 10 Mey: kembangin dork nya biar vuln"
   echo -e $okegreen"[10:06, 7/25/2019] S1XT33N: Filenya?"
   echo -e $okegreen"[10:06, 7/25/2019] S1XT33N: Png?"
   echo -e $okegreen"[10:06, 7/25/2019] 10 Mey: hmm"
   echo -e $okegreen"[10:06, 7/25/2019] 10 Mey: seterah webnya su"
   echo -e $okegreen"[10:07, 7/25/2019] S1XT33N: Okok"
   echo -e $okegreen"[10:07, 7/25/2019] S1XT33N: Nyoba dulu"
   echo -e $okegreen"[10:08, 7/25/2019] 10 Mey: ye"
   echo -e $okegreen"[10:32, 7/25/2019] S1XT33N: 😕"
   echo -e $okegreen"[10:34, 7/25/2019] 10 Mey: http://indox.mywebcommunity.org/# ini Cuk"
   echo -e $okegreen"[10:35, 7/25/2019] S1XT33N: Uah"
   echo -e $okegreen"[10:36, 7/25/2019] S1XT33N: http://welcomenightclub.everton.com/ :v"
   echo -e $okegreen"[10:36, 7/25/2019] 10 Mey: :v"
   echo -e $okegreen"[10:37, 7/25/2019] 10 Mey: Nick w Ga ada Su"
echo -e $okegreen"[10:37, 7/25/2019] 10 Mey: Take Over Github :v"
echo -e $okegreen"[11:05, 7/25/2019] S1XT33N: 🤣"
echo -e $okegreen"[11:05, 7/25/2019] S1XT33N: 🤣"
echo -e $okegreen"[12:19, 7/25/2019] 10 Mey: awokoaw su"
}
#D45H7
sid(){
echo -e $okegreen"[12:09, 7/25/2019] Arya-kun: Akun mati"
echo -e $okegreen"[12:10, 7/25/2019] +62 823-5248-2328: 😅😅"
echo -e $okegreen"[12:11, 7/25/2019] Arya-kun: Di sini mem lama D45H7 tolong angkat jari 👆"
echo -e $okegreen"[12:11, 7/25/2019] +62 895-3911-36695: 🖕🏼"
echo -e $okegreen"[12:12, 7/25/2019] +62 823-5248-2328: bukan jari tengah juga kaleee🤦🏻‍♂"
echo -e $okegreen"[12:12, 7/25/2019] +62 895-3911-36695: Oh salah ya 🤣 yaudah maap🙁"
echo -e $okegreen"[12:12, 7/25/2019] +62 895-3911-36695: 👆🏼"
echo -e $okegreen"[12:13, 7/25/2019] +62 823-5248-2328: nahhh"
echo -e $okegreen"[12:13, 7/25/2019] Arya-kun: Hwhw"
echo -e $okegreen"[12:13, 7/25/2019] Arya-kun: @+62 856-9234-8975 jugak ya?🤔"
echo -e $okegreen"[12:14, 7/25/2019] +62 895-3911-36695: Udah ga aktif maybe"
echo -e $okegreen"[12:14, 7/25/2019] Arya-kun: Hmm🤔"
echo -e $okegreen"[12:15, 7/25/2019] +62 895-3911-36695: Jarang nongol juga dia"
echo -e $okegreen"[12:21, 7/25/2019] +62 812-3829-9995: ."
echo -e $okegreen"[12:22, 7/25/2019] +62 823-5248-2328: mungkin dah keciduk.. 😁"
echo -e $okegreen"[12:28, 7/25/2019] +62 897-5591-930: MATEMATIKA"
echo -e $okegreen"[12:29, 7/25/2019] +62 895-6151-14130: Gw mem baru om😩"
}

#load  
load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}

#INTRO
intro(){
    clear
    echo -e $okegreen" __           _               __    __      "
sleep 0.25
    echo -e $okegreen"/ _\ __ _  __| | __ _ _ __   / / /\ \ \__ _ "
sleep 0.25
    echo -e $okegreen"\ \ / _  |/ _  |/ _  |  _ \  \ \/  \/ / _  |"
sleep 0.25
    echo -e $okegreen"_\ \ (_| | (_| | (_| | |_) |  \  /\  / (_| |"
sleep 0.25
    echo -e $okegreen"\__/\__,_|\__,_|\__,_| .__/    \/  \/ \__,_|"
sleep 0.25
    echo -e $okegreen"                     |_|                    "
sleep 1
    echo -e $okegreen"||========================================||"
    sleep 0.25
    echo -e $okegreen"||=WELCOME TO TOOLS SADAP WA BY Tampansky=||"
    sleep 0.25
    echo -e $okegreen"||========================================||"
    sleep 0.25
}

#outro
    intro
    sleep 1
    echo -e $okegreen        "    Author : Tampansky   "
    sleep 0.25
    echo -e $okegreen        "    Team : PSCT OFFIC      "
    sleep 0.25
    echo -e $okegreen        "Thanks To All Member PSCT"
    sleep 1
    echo -e $okegreen"Masukan Target Nya"
    echo -e $red"Note: +62 Ga Pake 0"
    read -p ">" u
    clear
    sleep 1
    echo -e $okegreen"Menganalisa..." 
    sleep 2
    clear
    echo -e $okegreen"NOMOR BIASA : 0$u"
    sleep 0.25    
    echo -e $okegreen"NOMOR WA : +62$u"
    sleep 0.25
    echo -e $okegreen"Pemilik : hadiprasetia"
    sleep 0.25
    echo -e $okegreen"Kartu : XL"
    sleep 0.25
    sleep 3
    echo -e $okegreen"Melanjutkan Untuk sadap wa ? y/n"$okegreen
    read -p ">" Dump
    if [ $Dump = "y"  ]; then 
    sha 
    else
    echo -e "kesalahan"
    sleep 1 
    clear
    fi 
    sha(){
    sleep 1
    echo -e $okegreen" SADAP WA ACTIVED"
    sleep 2
    echo -e $okegreen"1.)Helky"
    sleep 0.25
    echo -e $okegreen"2.)S1XT3N"
    sleep 0.25
    echo -e $okegreen"3.)PSCT officiall"
    sleep 0.25
    echo -e $okegreen"4.)D45H7 officiall"
    sleep 0.25
    echo -e $okegreen"PILIH CHAT!!!"
    echo -n -e ">"
    read -e lol
    case $lol in
    ("1")
    helky
    ;;
    ("2")
     sis
     ;;
     ("3")
     psct
     ;;
     ("4")
     sid
     ;;
    esac
    }
