#!/bin/bash
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#load  
load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}
#INTRO
intro(){
    echo -e $green" __           _               __    __      "
sleep 0.25
    echo -e $green"/ _\ __ _  __| | __ _ _ __   / / /\ \ \__ _ "
sleep 0.25
    echo -e $green"\ \ / _  |/ _  |/ _  |  _ \  \ \/  \/ / _  |"
sleep 0.25
    echo -e $green"_\ \ (_| | (_| | (_| | |_) |  \  /\  / (_| |"
sleep 0.25
    echo -e $green"\__/\__,_|\__,_|\__,_| .__/    \/  \/ \__,_|"
sleep 0.25
    echo -e $green"                     |_|                    "
sleep 1
    echo -e $green"||========================================||"
    sleep 0.25
    echo -e $green"||=WELCOME TO TOOLS SADAP WA BY Tampansky=||"
    sleep 0.25
    echo -e $green"||========================================||"
    sleep 0.25
}
sadap(){
    echo -e $green"///////////////////////////"
    sleep 0.25
    echo -e $green"    Author : Tampansky   "
    sleep 0.25
    echo -e $green"    Team : PSCT OFFIC      "
    sleep 0.25
    echo -e $green"Thanks To All Member PSCT"
    sleep 0.25
    echo -e $green"//////////////////////////"
    sleep 1
    echo -e $green"Masukan Target Mu!1!1!1"
    read -p ">" u
    echo -e $green"Menganalisa..." 
    sleep 2
    clear
    echo -e $green"NOMOR BIASA : $u"
    echo -e $green"NOMOR WA : +62$u"
    sleep 1
    echo
    echo -e "1.Dump Chat"
    echo -e "2.Keluar"
    read -p ">" p 
    if [ $p = "1" ]; then 
    echo -e $green "SEDANG MASA PERBARUAN TQ."
    else
    echo "SYNTAX EROR 404"
    fi 
    mulai

    if [ $p = "2" ]; then
    echo -e $green"Thanks To Play My Tools"
    else
    echo "SYNTAX EROR 404"
    fi
    mulai
    
}
echo -e $green"WELCOME TO SadapSkyWA"
echo -e $green"LANJUT KE TOOLSNYA?"
read -p "y/n?" tod
if [ $tod = "y" ]; then 
intro
else 
echo -e "TOLOOOOOONG KIAMATTT!1!1!1!"
fi
