#!/bin/bash
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#load  
load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}
#INTRO
intro(){
    echo -e $okegreen" __           _               __    __      "
sleep 0.25
    echo -e $okegreen"/ _\ __ _  __| | __ _ _ __   / / /\ \ \__ _ "
sleep 0.25
    echo -e $okegreen"\ \ / _  |/ _  |/ _  |  _ \  \ \/  \/ / _  |"
sleep 0.25
    echo -e $okegreen"_\ \ (_| | (_| | (_| | |_) |  \  /\  / (_| |"
sleep 0.25
    echo -e $okegreen"\__/\__,_|\__,_|\__,_| .__/    \/  \/ \__,_|"
sleep 0.25
    echo -e $okegreen"                     |_|                    "
sleep 1
    echo -e $okegreen"||========================================||"
    sleep 0.25
    echo -e $okegreen"||=WELCOME TO TOOLS SADAP WA BY Tampansky=||"
    sleep 0.25
    echo -e $okegreen"||========================================||"
    sleep 0.25
    sadap
}
sadap(){
    echo -e $okegreen"///////////////////////////"
    sleep 0.25
    echo -e $okegreen"    Author : Tampansky   "
    sleep 0.25
    echo -e $okegreen"    Team : PSCT OFFIC      "
    sleep 0.25
    echo -e $okegreen"Thanks To All Member PSCT"
    sleep 0.25
    echo -e $okegreen"//////////////////////////"
    sleep 1
    echo -e $okegreen"Masukan Target Mu!1!1!1"
    read -p ">" u
    echo -e $okegreen"Menganalisa..." 
    sleep 2
    clear
    echo -e $okegreen"NOMOR BIASA : $u"
    echo -e $okegreen"NOMOR WA : +62$u"
    sleep 1
    echo
    echo -e "1.Dump Chat"
    echo -e "2.Keluar"
    read -p ">" p 
    if [ $p = "1" ]; then 
    echo -e $okegreen "SEDANG MASA PERBARUAN TQ."
    else
    echo "SYNTAX EROR 404"
    fi 

    if [ $p = "2" ]; then
    echo -e $okegreen"Thanks To Play My Tools"
    else
    echo "SYNTAX EROR 404"
    fi

}
echo -e $okegreen"WELCOME TO SadapSkyWA"
echo -e $okegreen"LANJUT KE TOOLSNYA?"
read -p "y/n?" tod
if [ $tod = "y" ]; then 
intro
else 
echo -e "TOLOOOOOONG KIAMATTT!1!1!1!"
fi
